### ISSUE TITLE
[Bug]: pena dont drive

### ISSUE THREAD

**Issue by Aggin856** [tiagomarked/CallYourCousin#2]
### MSCLoader version

v.231210-01

### Description

When he arrive and get in his car he doesnt drive. I try to find out which mod is conflict and i find out that its mop.

### Attachments

[output_log.txt](https://github.com/user-attachments/files/17265876/output_log.txt)

**Comment by tiagomarked** [comment]
Hello, I've noticed you're using Modern Optimization Plugin, this has been abandoned and its behavior is very unpredictable on the latest version of the game, as such using it is not supported.
Thank you for reminding me of this, I have added this disclaimer to the mod's description.

As for a fix: uninstall MOP and launch the game to confirm if it's now working.
If you still encounter issues without using MOP, please submit a new bug report.
