### ISSUE TITLE
[Bug]: he wont drive after i get in.

### ISSUE THREAD

**Issue by Benchove** [tiagomarked/CallYourCousin#3]
### MSCLoader version

1.2.14

### Description

When you call him from anywhere he will show up and stop for you but when you get in he will not move ever and even if you get out he still refuses to move and wont move again unless you restart the game.

### Attachments

[uncapped_MedalTVMySummerCar20241016172009.zip](https://github.com/user-attachments/files/17404409/uncapped_MedalTVMySummerCar20241016172009.zip)

**Comment by tiagomarked** [comment]
Missing output_log.txt file.
