### ISSUE TITLE
[Bug]: Cousin runs off the road

### ISSUE THREAD

**Issue by oporep** [tiagomarked/CallYourCousin#5]
### MSCLoader version

1.2.14

### Description

When I was driving with my cousin to a bar, and after 2-3 kilometers he flew off the road and almost crashed into a tree. He started driving in different directions and got onto the road. Five minutes later the same thing happened again. Also my MOP is missing.

### Attachments

[output_log.txt](https://github.com/user-attachments/files/17850179/output_log.txt)

**Comment by tiago-martinez** [comment]
This problem is most likely unrelated to the mod itself and is expected base game behavior.
